version: '3.8'

services:
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: denned233
      POSTGRES_DB: postgres
    ports:
      - '5432:5432' # Проброс порта для подключения к базе данных
    volumes:
      - pgdata:/var/lib/postgresql/data # Сохранение данных вне контейнера
    networks:
      - app_network # Общая сеть для сервисов

  sales_service:
    build:
      context: . # Контекст сборки
      dockerfile: Dockerfile # Используемый Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Host=postgres_db;Port=5432;Database=postgres;Username=postgres;Password=denned233"
      # Добавлено соединение для базы данных через имя сервиса
    ports:
      - '8080:8080' # API порт
      - '8081:8081' # Swagger или другие сервисы
    networks:
      - app_network # Общая сеть для сервисов
    depends_on:
      - postgres_db # Указывает, что сервис должен ожидать, пока PostgreSQL станет доступен

volumes:
  pgdata: # Том для сохранения данных PostgreSQL

networks:
  app_network: # Общая сеть для взаимодействия сервисов
    driver: bridge
